steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--target",
        "prod",
        "-t",
        "gcr.io/$PROJECT_ID/listle:$SHORT_SHA",
        ".",
      ]
  # tag image as latest
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "gcr.io/$PROJECT_ID/listle:$SHORT_SHA",
        "gcr.io/$PROJECT_ID/listle:latest",
      ]
  # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/listle:$SHORT_SHA"]

images:
  - "gcr.io/$PROJECT_ID/listle:$SHORT_SHA"
