steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/listle-tester",
        "--target",
        "tester",
        ".",
      ]
    timeout: 500s

  - name: "gcr.io/cloud-builders/docker"
    args: ["run", "gcr.io/$PROJECT_ID/listle-tester", "flake8"]
    env:
      - ENV=test
      - FLASK_ENV=test

  - name: "gcr.io/cloud-builders/docker"
    args: ["run", "gcr.io/$PROJECT_ID/listle-tester", "pytest"]
    env:
      - ENV=test
      - FLASK_ENV=test
