version: "3.4"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/creds/creds.json
    env_file:
      - ./creds/env
